# Use the official maven/Java image to create a build artifact.
FROM maven:3.6.3-jdk-8 as builder
WORKDIR /app
COPY . .
RUN mvn clean package

# Use the official OpenJDK image to run the application
FROM openjdk:8-jdk-alpine
COPY --from=builder /app/target/*.jar /app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
